# Generated by Django 6.0.2 for Solfasol calendar app.

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CalendarEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=180)),
                ("description", models.TextField(blank=True)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("education", "Eğitim"),
                            ("community", "Topluluk"),
                            ("external", "Dış etkinlik"),
                            ("other", "Diğer"),
                        ],
                        default="community",
                        max_length=24,
                    ),
                ),
                ("starts_at", models.DateTimeField()),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("is_all_day", models.BooleanField(default=False)),
                ("location_name", models.CharField(blank=True, max_length=160)),
                ("location_address", models.TextField(blank=True)),
                ("link_url", models.URLField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Taslak"), ("published", "Yayında"), ("canceled", "İptal")],
                        default="draft",
                        max_length=24,
                    ),
                ),
            ],
            options={
                "verbose_name": "Takvim etkinliği",
                "verbose_name_plural": "Takvim etkinlikleri",
                "ordering": ["starts_at", "title"],
            },
        ),
    ]
