# Generated by Django 6.0.2 on 2026-05-10 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memberofferintent',
            options={'ordering': ['-created_at'], 'verbose_name': 'Üye teklif talebi', 'verbose_name_plural': 'Üye teklif talepleri'},
        ),
    ]
