# Generated by Django 5.2 on 2026-05-12 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coop', '0004_make_offer_fulfillment_date_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberofferintent',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='procurementoffer',
            name='target_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='procurementoffer',
            name='unit_price',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
