# Generated by Django 6.0.2 on 2026-05-10 06:04

import django.db.models.deletion
import members.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.CharField(default=members.models.generate_invitation_token, max_length=80, unique=True)),
                ('label', models.CharField(blank=True, help_text='WhatsApp, Facebook veya topluluk adı gibi kaynak etiketi.', max_length=120)),
                ('status', models.CharField(choices=[('active', 'Aktif'), ('revoked', 'İptal edildi')], default='active', max_length=20)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL)),
                ('revoked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_invitations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Davet linki',
                'verbose_name_plural': 'Davet linkleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_coop_member', models.BooleanField(default=False, verbose_name='Kooperatif üyesi')),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_profiles', to='members.invitation')),
                ('invited_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_members', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Üye profili',
                'verbose_name_plural': 'Üye profilleri',
            },
        ),
    ]
