# Generated by Django 6.0.2 on 2026-05-10 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='invited_by',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
